param(
  [switch]$Force
)

$ErrorActionPreference = 'Stop'

function Test-IsAdmin {
  $currentIdentity = [Security.Principal.WindowsIdentity]::GetCurrent()
  $principal = New-Object Security.Principal.WindowsPrincipal($currentIdentity)
  return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

$hostsPath = Join-Path $env:SystemRoot 'System32\drivers\etc\hosts'

if (-not (Test-Path $hostsPath)) {
  throw "hosts file not found at $hostsPath"
}

$entries = @(
  @{ Hostname = 'binaries.prisma.sh'; IPs = @('104.20.43.103', '172.66.156.100') },
  @{ Hostname = 'binaries-failover.prisma.sh'; IPs = @('104.20.43.103', '172.66.156.100') }
)

$beginMarker = '# BEGIN prisma-dns-workaround'
$endMarker = '# END prisma-dns-workaround'

if (-not (Test-IsAdmin)) {
  Write-Host 'This script must be run as Administrator to edit the hosts file.' -ForegroundColor Yellow
  Write-Host 'Re-run from an elevated PowerShell:' -ForegroundColor Yellow
  Write-Host "  powershell -NoProfile -ExecutionPolicy Bypass -File scripts\fixPrismaDns.ps1" -ForegroundColor Yellow
  exit 1
}

$original = Get-Content -LiteralPath $hostsPath -ErrorAction Stop

$filtered = @()
$inBlock = $false
foreach ($line in $original) {
  if ($line.Trim() -eq $beginMarker) { $inBlock = $true; continue }
  if ($line.Trim() -eq $endMarker) { $inBlock = $false; continue }
  if (-not $inBlock) { $filtered += $line }
}

$newBlock = @()
$newBlock += $beginMarker
$newBlock += "# Workaround for Prisma engine downloads when local DNS cannot resolve binaries.prisma.sh"
$newBlock += "# Generated by scripts\\fixPrismaDns.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
foreach ($entry in $entries) {
  foreach ($ip in $entry.IPs) {
    $newBlock += ("{0} {1}" -f $ip, $entry.Hostname)
  }
}
$newBlock += $endMarker

$next = @($filtered + '' + $newBlock + '')

Set-Content -LiteralPath $hostsPath -Value $next -Encoding ASCII

try {
  ipconfig /flushdns | Out-Null
} catch {
  Write-Host 'Warning: ipconfig /flushdns failed; continuing.' -ForegroundColor Yellow
}

Write-Host 'Prisma DNS workaround installed. You can now run:' -ForegroundColor Green
Write-Host '  npm run prisma:generate' -ForegroundColor Green
