import { prisma } from "../lib/prisma";
import { randomUUID } from "crypto";

async function main() {
  const user = await prisma.user.findFirst({ select: { id: true, email: true, name: true } });
  if (!user) throw new Error("No users found to seed pending payment.");

  const gatewayReference = `SMOKE-TOPUP-${randomUUID()}`;

  const created = await prisma.pendingPayment.create({
    data: {
      id: randomUUID(),
      // id: auto-generated by Prisma schema if configured
      userId: user.id,
      amount: 5000,
      status: "pending",
      transactionType: "TOPUP",
      paymentMethod: "Bank Transfer",
      gatewayReference,
      metadata: {},
      createdAt: new Date(),
      updatedAt: new Date(),
    } as any,
  });

  console.log("Seeded pending payment:", { id: created.id, userId: created.userId, amount: created.amount, status: created.status, transactionType: created.transactionType });
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
