import type { Prisma } from "@prisma/client";
import { randomUUID } from "crypto";

export const adminSettingsSeedData: Prisma.AdminSettingsCreateInput[] = [
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "CASH_WITHDRAWAL_FEE",
    settingValue: "100",
    description: "Default cash withdrawal fee",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "BPT_WITHDRAWAL_FEE",
    settingValue: "0",
    description: "Default BPT withdrawal fee",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "MAX_TRANSFER_AMOUNT",
    settingValue: "500000",
    description: "Maximum transfer amount",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "AUTO_WITHDRAWAL_THRESHOLD",
    settingValue: "100000",
    description: "Auto-withdrawal threshold",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "csp_tier_model_enabled",
    settingValue: "false",
    description: "Enable CSP tier model",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "csp_contribution_multiplier",
    settingValue: "20",
    description: "CSP contribution multiplier",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "csp_min_contribution_right",
    settingValue: "10000",
    description: "Minimum CSP contribution right",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "csp_require_kyc",
    settingValue: "false",
    description: "Require KYC for CSP tier model",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "csp_require_auto_debit",
    settingValue: "false",
    description: "Require auto debit for CSP tier model",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "csp_require_auto_contribute",
    settingValue: "false",
    description: "Require auto contribute for CSP tier model",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "csp_default_broadcast_hours",
    settingValue: "48",
    description: "Default CSP broadcast hours",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "csp_auto_extension_hours",
    settingValue: "48",
    description: "Auto extension hours",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "csp_max_auto_extensions",
    settingValue: "3",
    description: "Maximum auto extensions",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "csp_default_cooling_months_min",
    settingValue: "12",
    description: "Default minimum cooling months",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "csp_default_cooling_months_max",
    settingValue: "24",
    description: "Default maximum cooling months",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "csp_sponsorship_required_count",
    settingValue: "100",
    description: "Required sponsor count for cooling reduction",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "csp_sponsorship_reduced_cooling_months",
    settingValue: "6",
    description: "Reduced cooling months for sponsorship",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "csp_sponsorship_requires_kyc",
    settingValue: "false",
    description: "Require KYC for sponsorship reduction",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "csp_sponsorship_requires_regular_plus",
    settingValue: "false",
    description: "Require Regular Plus for sponsorship reduction",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "csp_sponsorship_auto_apply",
    settingValue: "false",
    description: "Auto apply sponsorship reduction",
  },
  {
    id: randomUUID(),
    updatedAt: new Date(),
    settingKey: "csp_badge_gifting_enabled",
    settingValue: "true",
    description: "Enable CSP badge gifting",
  },
];
